/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAguaRouteImport } from './routes/_authenticated/agua'
import { Route as AuthenticatedCustosRouteImport } from './routes/_authenticated/custos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLavagemRouteImport } from './routes/_authenticated/lavagem'
import { Route as AuthenticatedRestauranteRouteImport } from './routes/_authenticated/restaurante'
import { Route as AuthenticatedTransporteRouteImport } from './routes/_authenticated/transporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAguaRoute = AuthenticatedAguaRouteImport.update({
  id: '/agua',
  path: '/agua',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustosRoute = AuthenticatedCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLavagemRoute = AuthenticatedLavagemRouteImport.update({
  id: '/lavagem',
  path: '/lavagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRestauranteRoute =
  AuthenticatedRestauranteRouteImport.update({
    id: '/restaurante',
    path: '/restaurante',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransporteRoute = AuthenticatedTransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agua': typeof AuthenticatedAguaRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lavagem': typeof AuthenticatedLavagemRoute
  '/restaurante': typeof AuthenticatedRestauranteRoute
  '/transporte': typeof AuthenticatedTransporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agua': typeof AuthenticatedAguaRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lavagem': typeof AuthenticatedLavagemRoute
  '/restaurante': typeof AuthenticatedRestauranteRoute
  '/transporte': typeof AuthenticatedTransporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agua': typeof AuthenticatedAguaRoute
  '/_authenticated/custos': typeof AuthenticatedCustosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lavagem': typeof AuthenticatedLavagemRoute
  '/_authenticated/restaurante': typeof AuthenticatedRestauranteRoute
  '/_authenticated/transporte': typeof AuthenticatedTransporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agua'
    | '/custos'
    | '/dashboard'
    | '/lavagem'
    | '/restaurante'
    | '/transporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agua'
    | '/custos'
    | '/dashboard'
    | '/lavagem'
    | '/restaurante'
    | '/transporte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agua'
    | '/_authenticated/custos'
    | '/_authenticated/dashboard'
    | '/_authenticated/lavagem'
    | '/_authenticated/restaurante'
    | '/_authenticated/transporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agua': {
      id: '/_authenticated/agua'
      path: '/agua'
      fullPath: '/agua'
      preLoaderRoute: typeof AuthenticatedAguaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos': {
      id: '/_authenticated/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AuthenticatedCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lavagem': {
      id: '/_authenticated/lavagem'
      path: '/lavagem'
      fullPath: '/lavagem'
      preLoaderRoute: typeof AuthenticatedLavagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurante': {
      id: '/_authenticated/restaurante'
      path: '/restaurante'
      fullPath: '/restaurante'
      preLoaderRoute: typeof AuthenticatedRestauranteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporte': {
      id: '/_authenticated/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof AuthenticatedTransporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAguaRoute: typeof AuthenticatedAguaRoute
  AuthenticatedCustosRoute: typeof AuthenticatedCustosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLavagemRoute: typeof AuthenticatedLavagemRoute
  AuthenticatedRestauranteRoute: typeof AuthenticatedRestauranteRoute
  AuthenticatedTransporteRoute: typeof AuthenticatedTransporteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAguaRoute: AuthenticatedAguaRoute,
  AuthenticatedCustosRoute: AuthenticatedCustosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLavagemRoute: AuthenticatedLavagemRoute,
  AuthenticatedRestauranteRoute: AuthenticatedRestauranteRoute,
  AuthenticatedTransporteRoute: AuthenticatedTransporteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
